version: '3'
services:
  secret:
    environment:
      - "DEVELOPMENT=true"
    volumes:
      - /tmp/secret:/tmp/secret
  myapp:
    build: .
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  db:
    ports:
      - "13306:3306"
