version: '3'
services:
  secret:
    environment:
      - "DEVELOPMENT=true"
    volumes:
      - /tmp/secret:/tmp/secret
  dkdk:
    build: .
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
