FROM golang:1.15
#ENV GOPROXY="https://proxy.golang.org"
ENV GOPROXY="https://goproxy.io,direct"
ARG DEBIAN_MIRROR="huaweicloud"
#ARG DEBIAN_MIRROR="aliyun"
COPY . /build
WORKDIR /build
RUN GO111MODULE="on" GOPROXY=$GOPROXY CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w"
RUN sed -i "s@http://ftp.debian.org@https://mirrors.$DEBIAN_MIRROR.com@g" /etc/apt/sources.list && \
sed -i "s@http://security.debian.org@https://mirrors.$DEBIAN_MIRROR.com@g" /etc/apt/sources.list && \
sed -i "s@http://deb.debian.org@https://mirrors.$DEBIAN_MIRROR.com@g" /etc/apt/sources.list && \
apt update && \
apt install -y upx
RUN upx binary
